In [ ]:
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [ ]:
arr1=np.arange(10)
print(arr1)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
my_list=list(range(10))
print(type(my_list))
print(type(arr1))

<class 'list'>
<class 'numpy.ndarray'>


In [ ]:
import numpy as np
import sys
S=range(1000)
print("Size of each element of list in bytes: ",sys.getsizeof(S))
print("Size of the whole element of list in bytes: ",sys.getsizeof(S)*len(S))
D=np.arange(1000)
print("Size of each element of the numpy array in bytes: ",D.itemsize)
print("Size of the whole element of numpy array in bytes: ",D.size*D.itemsize)

Size of each element of list in bytes:  48
Size of the whole element of list in bytes:  48000
Size of each element of the numpy array in bytes:  8
Size of the whole element of numpy array in bytes:  8000


In [ ]:
a=np.array([[[1,2,3,4,5],[1,2,3,4,5]],[[1,2,3,4,5],[1,2,3,4,5]]])
print(a.ndim)

3


In [ ]:
arr2=arr = np.array([1, 2, 3, 4], ndmin=5)
print(arr2)
print(arr2.ndim)

[[[[[1 2 3 4]]]]]
5


In [ ]:
arr3=np.arange(50)
arr3=arr3.reshape(5,10)
print(arr3)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]]


In [ ]:
arr4=np.array([[[1,2,3,4],[1,2,3,4]],[[1,2,3,4],[1,2,3,4]]])
print(arr4.ndim)

3


In [ ]:
import numpy as np
arr5 = np.array([11,2,3,4] , ndmin=5)
print(arr5)
print('number of dimensions:', arr5.ndim)

[[[[[11  2  3  4]]]]]
number of dimensions: 5


In [ ]:
data = np.array([[1.5, -0.1, 3], [0,-3, 6.5]])
print("Shape",data.shape)
print("Type= ",data.dtype)
print("Data = ",data)
print("\nAns1 = ",data * 10)
print("\nAns2 = ",data + data)

Shape (2, 3)
Type=  float64
Data =  [[ 1.5 -0.1  3. ]
 [ 0.  -3.   6.5]]

Ans1 =  [[ 15.  -1.  30.]
 [  0. -30.  65.]]

Ans2 =  [[ 3.  -0.2  6. ]
 [ 0.  -6.  13. ]]


In [ ]:
import numpy as np
a = np.arange(12).reshape(3,4)
print("a= \n",a)
b = a > 4
print("b= \n",b)
print("a[b]= \n",a[b]) # 1d array
a[b] = 1
print("a= \n",a)

a= 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
b= 
 [[False False False False]
 [False  True  True  True]
 [ True  True  True  True]]
a[b]= 
 [ 5  6  7  8  9 10 11]
a= 
 [[0 1 2 3]
 [4 1 1 1]
 [1 1 1 1]]


In [ ]:
my_list = [1, 2, 3, 4, 5]
arr = np.array(my_list)
print(type(arr))
print(arr)
print("\n", arr.dtype)

<class 'numpy.ndarray'>
[1 2 3 4 5]

 int64


In [ ]:
zeros_arr = np.zeros((5,2))
eros_arr = np.zeros(5)
print(zeros_arr)

zeros_arr = np.zeros((2, 3))
print(zeros_arr)

print("Data type of the array: ",zeros_arr.dtype)

zeros_arr_int = np.zeros((3,3))
print("\nArray of zeros with integer elements:\n", zeros_arr_int)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]
[[0. 0. 0.]
 [0. 0. 0.]]
Data type of the array:  float64

Array of zeros with integer elements:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
ones_arr = np.ones(6)
print(ones_arr)

ones_arr = np.ones((3,2,4))
print("\n", ones_arr)
print("\n ndim = ",ones_arr.ndim)

print("Data type of the array: ",ones_arr.dtype)

ones_arr_int = np.ones((2,2), dtype=np.int16)
print("\nArray of ones with integer elements:\n", ones_arr_int)

[1. 1. 1. 1. 1. 1.]

 [[[1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]]]

 ndim =  3
Data type of the array:  float64

Array of ones with integer elements:
 [[1 1]
 [1 1]]


In [ ]:
empty_arr = np.empty((3, 2))
print(empty_arr)
print("Data type of the array: ",empty_arr.dtype)

[[0. 0.]
 [0. 0.]
 [0. 0.]]
Data type of the array:  float64


In [ ]:
identity_matrix = np.eye(3)
print(identity_matrix)

identity_matrix1 = np.eye(4) # Added the required argument
print("\n",identity_matrix1)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
import numpy as np
arr6 = np.array([1,2,3], dtype = np.float64)
arr7 =np.array([1,2,3], dtype = np.int32)
print(arr6.dtype)
print(arr7.dtype)

float64
int32


In [ ]:
arr = np.array([1,2,3])
print("Before converting: ",arr,arr.dtype)

new_arr = arr.astype('f')
print("After converting:" , new_arr, new_arr.dtype)


Before converting:  [1 2 3] int64
After converting: [1. 2. 3.] float32


In [ ]:
arr = np.array([1.1, 2.2, 3.3])
print("Before converting: ",arr,arr.dtype)

new_arr = arr.astype('i')
print("After converting:" , new_arr, new_arr.dtype)

Before converting:  [1.1 2.2 3.3] float64
After converting: [1 2 3] int32


In [ ]:
arr = np.array(['1.1', '2.2', '-3.3'])
print("Before converting: ", arr, arr.dtype)

new_arr = arr.astype('f')
print("After converting:" , new_arr, new_arr.dtype)

Before converting:  ['1.1' '2.2' '-3.3'] <U4
After converting: [ 1.1  2.2 -3.3] float32


In [ ]:
arr = np.array(['1.1', '2.2', 'abc'])
print("Before converting: ", arr, arr.dtype)
try:
  new_arr = arr.astype(np.float64)
  print("After converting: ",new_arr, new_arr.dtype)
except ValueError as e:
  print("Conversion failed:", e)

Before converting:  ['1.1' '2.2' 'abc'] <U3
Conversion failed: could not convert string to float: np.str_('abc')


In [ ]:
arr1 = np.arange(10)
arr2 = np.random.randn(10)
print("array 1\n",arr1, arr1.dtype)
print("array 2\n",arr2, arr2.dtype)

array 1
 [0 1 2 3 4 5 6 7 8 9] int64
array 2
 [-0.68423967 -0.01083876 -1.05325495  0.96835856 -0.48808955 -1.37746441
  0.20371983  1.34456193 -0.08217552  0.26320251] float64


In [ ]:
str_arr = np.array(['hello', 'world', 'numpy'])
print(str_arr)

['hello' 'world' 'numpy']


In [ ]:
import numpy as np
a = np.array([1., 2., 3., 4.])
b=np.array([5., 6., 7., 8.])
print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a**b)

[ 6.  8. 10. 12.]
[-4. -4. -4. -4.]
[ 5. 12. 21. 32.]
[0.2        0.33333333 0.42857143 0.5       ]
[1.0000e+00 6.4000e+01 2.1870e+03 6.5536e+04]


In [ ]:
c = np.array([1., 2., 3., 4.])
print(a+1)
print(a-1)
print(a*2)
print(a/2)
print(a**2)
print(1/a)

[2. 3. 4. 5.]
[0. 1. 2. 3.]
[2. 4. 6. 8.]
[0.5 1.  1.5 2. ]
[ 1.  4.  9. 16.]
[1.         0.5        0.33333333 0.25      ]


In [ ]:
import numpy as np
arr = np.arange(12)
newarr = arr.reshape(4,3)
print(newarr)
newarr = arr.reshape((4,3),order='F')
print("\n",newarr)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]

 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [ ]:
import numpy as np
arr = np.array([[1,2,3,4,9,20],[5,6,7,8,11,12]])
print(arr)
newarr = arr.reshape(3,2,2)
print("\n", newarr)
newarr1 = newarr.reshape(3,-1)
print("\n reshape(3,-1) \n",newarr1)


[[ 1  2  3  4  9 20]
 [ 5  6  7  8 11 12]]

 [[[ 1  2]
  [ 3  4]]

 [[ 9 20]
  [ 5  6]]

 [[ 7  8]
  [11 12]]]

 reshape(3,-1) 
 [[ 1  2  3  4]
 [ 9 20  5  6]
 [ 7  8 11 12]]


In [ ]:
import numpy as np

In [ ]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.arange(28).reshape(7, 4)
print(names)
print("data = \n",data)
print("names bool = \n",data[names=='Bob'])
print("names == 'Bob' ,2:\n",data[names == 'Bob' ,2:])
print("names == 'Bob' ,3:\n",data[names == 'Bob' ,3:])


['Bob' 'Joe' 'Will' 'Bob' 'Will' 'Joe' 'Joe']
data = 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]]
names bool = 
 [[ 0  1  2  3]
 [12 13 14 15]]
names == 'Bob' ,2:
 [[ 2  3]
 [14 15]]
names == 'Bob' ,3:
 [[ 3]
 [15]]


In [ ]:
import numpy as np
names = np.array(['Bob','Joe','Will','Bob','Will','Joe','Joe'])
data = np.arange(28).reshape(7,4)
print(data[names != 'Bob'])
print("\n",data[~(names == 'Bob')])
data[names != 'Bob'] = -1
print("\ndata= \n",data)

[[ 4  5  6  7]
 [ 8  9 10 11]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]]

 [[ 4  5  6  7]
 [ 8  9 10 11]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]]

data= 
 [[ 0  1  2  3]
 [-1 -1 -1 -1]
 [-1 -1 -1 -1]
 [12 13 14 15]
 [-1 -1 -1 -1]
 [-1 -1 -1 -1]
 [-1 -1 -1 -1]]


In [ ]:
import numpy as np
names = np.array(['Alice','Bob','Charlie','David'])
ages = np.array([25.5, 30, 28.2, 35])
older_than_29=ages>29
print("People older then 29:",names[older_than_29])
names_to_select=(names=='Alice') | (names == 'Charlie')
print("Ages of Alice aand Charlie:",ages[names_to_select])

People older then 29: ['Bob' 'David']
Ages of Alice aand Charlie: [25.5 28.2]


In [ ]:
import numpy as np
city_names = np.array(['New York', 'Los Angeles', 'Chicago', 'Houston'])
temperatures =  np.array([25, 32, 28, 35])
hot_threshold = 30
hot_cities_bool = temperatures > hot_threshold
print("Boolean array for hot cities:", hot_cities_bool)
hot_cities = city_names[hot_cities_bool]
print("Hot cities:", hot_cities)

Boolean array for hot cities: [False  True False  True]
Hot cities: ['Los Angeles' 'Houston']


In [ ]:
city_names = np.array(['New York', 'Los Angeles', 'Chicago', 'Houston'])
temperature = np.array([-25, 32, -28, 35])
negative_temp_indices = temperature < 0
temperature[negative_temp_indices] = 0
print("Updated temperatures:", temperature)

Updated temperatures: [ 0 32  0 35]


In [ ]:
arr = np.arange(32).reshape(8,4)
print("arr= \n",arr)
print("\n arr[[1,2,7,2]]=",arr[[1, 5, 7,2]])
print("\n arr[[1,5,7,2]][:,[0,3,1,2]]= \n",arr[[1,5,7,2]][:,[0,3,1,2]])
print("\n arr[[-3,-5,-7]]\n",arr[[-3, -5, -7]])
arr[[1,5,7,2]]=1
print("\n arr= \n",arr)

arr= 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]

 arr[[1,2,7,2]]= [[ 4  5  6  7]
 [20 21 22 23]
 [28 29 30 31]
 [ 8  9 10 11]]

 arr[[1,5,7,2]][:,[0,3,1,2]]= 
 [[ 4  7  5  6]
 [20 23 21 22]
 [28 31 29 30]
 [ 8 11  9 10]]

 arr[[-3,-5,-7]]
 [[20 21 22 23]
 [12 13 14 15]
 [ 4  5  6  7]]

 arr= 
 [[ 0  1  2  3]
 [ 1  1  1  1]
 [ 1  1  1  1]
 [12 13 14 15]
 [16 17 18 19]
 [ 1  1  1  1]
 [24 25 26 27]
 [ 1  1  1  1]]


In [ ]:
import numpy as np
arr = np.arange(12).reshape((3,4))
print(arr)
print("Transpose using .T")
print(arr.T)
print("Transpose using transpose() function")
print(np.transpose(arr))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Transpose using .T
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
Transpose using transpose() function
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [ ]:
arr1=np.transpose(arr,(1,0))
print(arr1)
arr2=np.transpose(arr,(0,1))
print(arr2)

[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [ ]:
arr = np.arange(12).reshape((2,3,2))
print(arr)
print("Transpose using .T")
arr3dT = arr.T
print(arr3dT)
print(arr3dT.shape)
print("Transpose using transpose() function")
print(np.transpose(arr))


[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]
Transpose using .T
[[[ 0  6]
  [ 2  8]
  [ 4 10]]

 [[ 1  7]
  [ 3  9]
  [ 5 11]]]
(2, 3, 2)
Transpose using transpose() function
[[[ 0  6]
  [ 2  8]
  [ 4 10]]

 [[ 1  7]
  [ 3  9]
  [ 5 11]]]


In [ ]:
import numpy as np
arr = np.arange(12).reshape(( 3,4))
print("Dot product of arr and arr2:")
print(np.dot(arr,arr.T))

Dot product of arr and arr2:
[[ 14  38  62]
 [ 38 126 214]
 [ 62 214 366]]


In [ ]:
import numpy as np
arr = np.arange(12).reshape((3,4))
print(arr)
print("Swap axes 0 and 1:")
print(np.swapaxes(arr,0,1))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Swap axes 0 and 1:
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [ ]:
import numpy as np
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[5,6],[7,8]])
result = np.multiply(arr1,arr2)
print(result)

[[ 5 12]
 [21 32]]


In [ ]:
result = np.matmul(arr1, arr2)
print("Result of matrix multiplication:")
print(result)
result1 = np.dot(arr1, arr2)
print("Result of matrix multiplication:")
print(result1)

Result of matrix multiplication:
[[19 22]
 [43 50]]
Result of matrix multiplication:
[[19 22]
 [43 50]]


In [ ]:
import pandas
mydataset = {
    'cars':["BMW","Volvo","Ford"],
    'passings':[3,7,2]
}
myvar = pandas.DataFrame(mydataset)
print(myvar)


    cars  passings
0    BMW         3
1  Volvo         7
2   Ford         2


In [ ]:
import pandas as pd
data = [10, 20, 30, 40,50]
series= pd.Series(data)
print(series)

0    10
1    20
2    30
3    40
4    50
dtype: int64


In [ ]:
import pandas as pd
data =[10, 20, 30, 40, 50]
series = pd.Series(data)
print("Series Representation:\n",series)
array_representation = series.values
index_object = series.index
print("Array Representation:",array_representation)
print("Index Object:",index_object)

Series Representation:
 0    10
1    20
2    30
3    40
4    50
dtype: int64
Array Representation: [10 20 30 40 50]
Index Object: RangeIndex(start=0, stop=5, step=1)


In [ ]:
a =[1, 7, 2]
myvar = pd.Series(a, index =["x","y","z"])
print(myvar)

x    1
y    7
z    2
dtype: int64


In [ ]:
data = [10, 20, 30, 40, 50]
index_labels = ['a', 'b', 'c', 'd', 'e']
series = pd.Series(data, index=index_labels)
print("Series Representation:\n", series)

Series Representation:
 a    10
b    20
c    30
d    40
e    50
dtype: int64


In [ ]:
print(series['b'])
print(series[['a','c','e']])

20
a    10
c    30
e    50
dtype: int64


In [ ]:
gt=series>25
print("series>25= \n",gt)
series_filtered = series[series>25]
print("Filtered Series:\n",series_filtered)

series_multiplied = series*2
print("Multiplied Series:\n",series_multiplied)

series>25= 
 a    False
b    False
c     True
d     True
e     True
dtype: bool
Filtered Series:
 c    30
d    40
e    50
dtype: int64
Multiplied Series:
 a     20
b     40
c     60
d     80
e    100
dtype: int64


In [ ]:
import numpy as np
print("series =\n",series)
series_sqrt=np.sqrt(series)
print("\nSeries after Applying Square Root\n:",series_sqrt)

series =
 a    10
b    20
c    30
d    40
e    50
dtype: int64

Series after Applying Square Root
: a    3.162278
b    4.472136
c    5.477226
d    6.324555
e    7.071068
dtype: float64


In [ ]:
population_dict={'California': 38332521, 'Texas': 26448193, 'New York': 19651127, 'Florida': 19552860, 'Illinois': 12882135 }
population = pd.Series(population_dict)
print(population)

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
dtype: int64


In [ ]:
print('California' in population)
print('Canada' in population)

True
False


In [ ]:
data = [10, np.nan, 30, np.nan, 50]
index_labels =['a', 'b', 'c', 'd', 'e']
series_with_nan = pd.Series(data, index=index_labels)
print(series_with_nan)
print("\nChecking for NaN values:\n",series_with_nan.isnull())
print("\nChecking for non-NaN values:",series_with_nan.notnull())

a    10.0
b     NaN
c    30.0
d     NaN
e    50.0
dtype: float64

Checking for NaN values:
 a    False
b     True
c    False
d     True
e    False
dtype: bool

Checking for non-NaN values: a     True
b    False
c     True
d    False
e     True
dtype: bool


In [ ]:
area_dict = {'California': 423967, 'Texas': 695662, 'New York': 141297,
'Florida': 170312, 'Illinois': 149995, 'North Carolina':123456}
area = pd.Series(area_dict)
print("Population Series:\n", population)
print("\nArea Series:\n", area)
population_density  = population / area
print("\nPopulation Density:\n", population_density)

Population Series:
 California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
dtype: int64

Area Series:
 California        423967
Texas             695662
New York          141297
Florida           170312
Illinois          149995
North Carolina    123456
dtype: int64

Population Density:
 California         90.413926
Florida           114.806121
Illinois           85.883763
New York          139.076746
North Carolina           NaN
Texas              38.018740
dtype: float64


In [ ]:
male_population_dict = {'California': 19000000, 'Texas': 13000000, 'New York': 9500000,
'Florida': 9600000, 'Illinois': 6300000}
female_population_dict = {'California': 19332521, 'Texas': 13448193, 'New York': 10151127,
'Florida': 9952860, 'Illinois': 6582135}
male_population = pd.Series(male_population_dict)
female_population = pd.Series(female_population_dict)

total_population = male_population + female_population
print("\nTotal Population:\n", total_population)


Total Population:
 California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
dtype: int64


In [ ]:
total_population.name = 'Population'
total_population.index.name = 'State'
print(total_population)

State
California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
Name: Population, dtype: int64


In [ ]:
obj = pd.Series([4.5, 7.2, -5.3, 3.6], index=['d', 'b', 'a', 'c'])
print(obj)
obj2 = obj.reindex(['a', 'b', 'c', 'd', 'e'])
print(obj2)

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64
a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64


In [ ]:
import pandas as pd
subject1 = pd.Series([80,75, 92, 68, 70, 95, 88], index={'Student 1', 'Student 2', 'Student 3', 'Student 4', 'Student 5', 'Student 6', 'Student 7'})
subject2 = pd.Series([72, 88, 79, 91, 65, 82, 76], index={'Student 1', 'Student 2', 'Student 3', 'Student 4', 'Student 5', 'Student 6', 'Student 7'})
subject3 = pd.Series([90, 68, 85, 73, 78, 92, 80], index={'Student 1', 'Student 2', 'Student 3', 'Student 4', 'Student 5', 'Student 6', 'Student 7'})
subject4 = pd.Series([65, 92, 82, 88, 75, 79, 85], index={'Student 1', 'Student 2', 'Student 3', 'Student 4', 'Student 5', 'Student 6', 'Student 7'})
subject5 = pd.Series([78, 70, 95, 62, 83, 86, 91], index={'Student 1', 'Student 2', 'Student 3', 'Student 4', 'Student 5', 'Student 6', 'Student 7'})
total_marks = subject1 + subject2 + subject3 + subject4 + subject5
print("Total Marks= \n", total_marks)
print("Total Marks for Each Student:")
for i, (student, marks) in enumerate(total_marks.items()):
    print(f"Student {i+1}: ({student}): {marks}")

Total Marks= 
 Student 1    385
Student 2    393
Student 5    433
Student 4    382
Student 3    371
Student 6    434
Student 7    420
dtype: int64
Total Marks for Each Student:
Student 1: (Student 1): 385
Student 2: (Student 2): 393
Student 3: (Student 5): 433
Student 4: (Student 4): 382
Student 5: (Student 3): 371
Student 6: (Student 6): 434
Student 7: (Student 7): 420


In [ ]:
import pandas as pd
data ={ "calories": [420, 380, 390], "duration": [50, 40, 45] }
df = pd.DataFrame(data)
print(df)

   calories  duration
0       420        50
1       380        40
2       390        45


In [ ]:
data = {'state': ['Ohio','Ohio','Ohio','Nevada','Nevada','Nevada'],
        'year': [2000, 2001, 2002, 2001, 2002, 2003],
        'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}
frame =pd.DataFrame(data)
print(frame)

    state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2


In [ ]:
frame = pd.DataFrame(data, columns=['year', 'state', 'pop'])
print(frame)

   year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2


In [ ]:
frame2 = pd.DataFrame(data, columns=['year', 'state', 'pop', 'debt'], index=['one', 'two', 'three', 'four', 'five', 'six'])
print(frame2)

       year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN
six    2003  Nevada  3.2  NaN


In [ ]:
print(frame2['year'])
print("\n", frame2['state'])
print("\n", frame2.state)

one      2000
two      2001
three    2002
four     2001
five     2002
six      2003
Name: year, dtype: int64

 one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
six      Nevada
Name: state, dtype: object

 one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
six      Nevada
Name: state, dtype: object


In [ ]:
import pandas as pd
data = {'state': ['Ohio','Ohio','Ohio','Nevada','Nevada','Nevada'],
        'year': [2000, 2001, 2002, 2001, 2002, 2003],
        'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}
frame2 = pd.DataFrame(data, columns=['year', 'state', 'pop', 'debt'], index=['one', 'two', 'three', 'four', 'five', 'six'])
print(frame2.loc['one'])
print(frame2.loc[['two','three']])

year     2000
state    Ohio
pop       1.5
debt      NaN
Name: one, dtype: object
       year state  pop debt
two    2001  Ohio  1.7  NaN
three  2002  Ohio  3.6  NaN


In [ ]:
frame2['dept'] = 12.4
print(frame2)

       year   state  pop debt  dept
one    2000    Ohio  1.5  NaN  12.4
two    2001    Ohio  1.7  NaN  12.4
three  2002    Ohio  3.6  NaN  12.4
four   2001  Nevada  2.4  NaN  12.4
five   2002  Nevada  2.9  NaN  12.4
six    2003  Nevada  3.2  NaN  12.4


In [ ]:
import numpy as np
frame2['dept']= np.arange(6.)
print(frame2)

       year   state  pop debt  dept
one    2000    Ohio  1.5  NaN   0.0
two    2001    Ohio  1.7  NaN   1.0
three  2002    Ohio  3.6  NaN   2.0
four   2001  Nevada  2.4  NaN   3.0
five   2002  Nevada  2.9  NaN   4.0
six    2003  Nevada  3.2  NaN   5.0


In [ ]:
val = pd.Series([-1.2, -1.5, -1.7], index=['two', 'four','five'])
frame2['debt'] = val
print(frame2)

       year   state  pop  debt  dept
one    2000    Ohio  1.5   NaN   0.0
two    2001    Ohio  1.7  -1.2   1.0
three  2002    Ohio  3.6   NaN   2.0
four   2001  Nevada  2.4  -1.5   3.0
five   2002  Nevada  2.9  -1.7   4.0
six    2003  Nevada  3.2   NaN   5.0


In [ ]:
frame2['eastern'] = frame2.state == 'ohio'
print(frame2)

       year   state  pop  debt  dept  eastern
one    2000    Ohio  1.5   NaN   0.0    False
two    2001    Ohio  1.7  -1.2   1.0    False
three  2002    Ohio  3.6   NaN   2.0    False
four   2001  Nevada  2.4  -1.5   3.0    False
five   2002  Nevada  2.9  -1.7   4.0    False
six    2003  Nevada  3.2   NaN   5.0    False


In [ ]:
pop = {'Nevada': {2001: 2.4, 2002: 2.9},
       'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}}
frame3 = pd.DataFrame(pop)
print(frame3)

      Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2000     NaN   1.5


In [ ]:
frame3 = pd.DataFrame(pop, index=[2001, 2002, 2003])
print(frame3)

      Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2003     NaN   NaN


In [ ]:
print(frame3.T)

        2001  2002  2003
Nevada   2.4   2.9   NaN
Ohio     1.7   3.6   NaN


In [ ]:
pdata = {'Ohio': frame3['Ohio'][:-1],
         'Nevada': frame3['Nevada'][:2]}
pd.DataFrame(pdata)

Ohio  Nevada
2001   1.7     2.4
2002   3.6     2.9

In [ ]:
data = np.arange(0,9).reshape(3,3)
index =['Ohio', 'Colorado', 'New York']
columns = ['one', 'two', 'three']
df = pd.DataFrame(data, index=index, columns=columns)
df.index.name = 'state'
df.columns.name = 'number'
print(df,"\n")

number    one  two  three
state                    
Ohio        0    1      2
Colorado    3    4      5
New York    6    7      8 



In [ ]:
s=pd.Series(np.arange(5), index =['a', 'b','c', 'd', 'e'])
print(s)
print("Index:", s.index)
print("Index Values:",s.index.values)
print("Is Unique:", s.index.is_unique)
print("Index  of 'c':",s.index.get_loc('c'))
print("Slice with 'b': 'd':",s['b':'d'])
print("Fancy indexing indexing with ['a', 'e]:", s[['a', 'e']])

a    0
b    1
c    2
d    3
e    4
dtype: int64
Index: Index(['a', 'b', 'c', 'd', 'e'], dtype='object')
Index Values: ['a' 'b' 'c' 'd' 'e']
Is Unique: True
Index  of 'c': 2
Slice with 'b': 'd': b    1
c    2
d    3
dtype: int64
Fancy indexing indexing with ['a', 'e]: a    0
e    4
dtype: int64


In [ ]:
import pandas as pd
import numpy as np
obj = pd.Series([4.5, 7.2, -5.3, 3.6], index=['d', 'b', 'a', 'c'])
print(obj)

obj2 = obj.reindex(['a','b','c','d','e'])
print(obj2)

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64
a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64


In [ ]:
obj3 = pd.Series(['blue','purple', 'yellow'], index =[0, 2, 4])
print(obj3)
obj4=obj3.reindex(range(6), method='ffill')
print(obj4)

0      blue
2    purple
4    yellow
dtype: object
0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object


In [ ]:
import pandas as pd
import numpy as np
obj = pd.Series([4.5, 7.2, -5.3, 3.6], index=['d', 'b', 'a', 'c'])
print(obj)
obj2 = obj.reindex(['a', 'b', 'c', 'd', 'e'])
print(obj2)

df = pd.DataFrame(np.arange(9).reshape((3, 3)),
                  index=['a', 'c', 'd'],
                  columns=['Ohio', 'Texas', 'California'])

df2 = df.reindex(columns=['Texas', 'Utah', 'California'])
print("\nReindexing columns:")
print(df2)

df3 = df.reindex(index=['a', 'b', 'c', 'd'], columns=["Dallas", 'Texas', 'Utah', 'California'])
print("\nReindexing both rows and columns:")
print(df3)

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64
a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

Reindexing columns:
   Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

Reindexing both rows and columns:
   Dallas  Texas  Utah  California
a     NaN    1.0   NaN         2.0
b     NaN    NaN   NaN         NaN
c     NaN    4.0   NaN         5.0
d     NaN    7.0   NaN         8.0


In [ ]:
obj = pd.Series(np.arange(5.), index =['a', 'b', 'c', 'd', 'e'])
new_obj = obj.drop('c')
print(new_obj)
obj.drop(['d', 'c'])

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64


a    0.0
b    1.0
e    4.0
dtype: float64

In [ ]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
index=['Ohio', 'Dallas', 'NJ', 'New York'],
columns=['one', 'two', 'three', 'four'])
data

one  two  three  four
Ohio        0    1      2     3
Dallas      4    5      6     7
NJ          8    9     10    11
New York   12   13     14    15

In [ ]:
data.drop(['NJ', 'Ohio'])

one  two  three  four
Dallas      4    5      6     7
New York   12   13     14    15

In [ ]:
data.drop('three', axis=1)

one  two  four
Ohio        0    1     3
Dallas      4    5     7
NJ          8    9    11
New York   12   13    15

In [7]:
import pandas as pd
import numpy as np
obj = pd.Series(np.arange(4.), index=['a', 'b', 'c', 'd'])
print("obj['b']= \n",obj['b'])
print("obj[1]= \n",obj[1])
print("obj[2:4]= \n",obj[2:4])
print("obj[['b', 'a', 'd']]= \n",obj[['b', 'a', 'd']])
print("obj[b:d]= \n",obj['b':'d'])
print("obj[[1, 3]]= \n",obj[[1, 3]])
print("obj[obj < 2]= \n",obj[obj < 2])

obj['b']= 
 1.0
obj[1]= 
 1.0
obj[2:4]= 
 c    2.0
d    3.0
dtype: float64
obj[['b', 'a', 'd']]= 
 b    1.0
a    0.0
d    3.0
dtype: float64
obj[b:d]= 
 b    1.0
c    2.0
d    3.0
dtype: float64
obj[[1, 3]]= 
 b    1.0
d    3.0
dtype: float64
obj[obj < 2]= 
 a    0.0
b    1.0
dtype: float64


/tmp/ipython-input-7-3769513972.py:5: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print("obj[1]= \n",obj[1])
/tmp/ipython-input-7-3769513972.py:9: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print("obj[[1, 3]]= \n",obj[[1, 3]])


In [10]:
data = pd.DataFrame(np.arange(24).reshape((6, 4)),
index=['Ohio', 'Dallas', 'Boston', 'NJ', 'New York', 'Austin'],
columns=['one', 'two', 'three', 'four'])
data

one  two  three  four
Ohio        0    1      2     3
Dallas      4    5      6     7
Boston      8    9     10    11
NJ         12   13     14    15
New York   16   17     18    19
Austin     20   21     22    23

In [11]:
data['two']

Ohio         1
Dallas       5
Boston       9
NJ          13
New York    17
Austin      21
Name: two, dtype: int64

In [12]:
data[1:5]

one  two  three  four
Dallas      4    5      6     7
Boston      8    9     10    11
NJ         12   13     14    15
New York   16   17     18    19

In [13]:
data.loc['Dallas', ['two', 'three']]

two      5
three    6
Name: Dallas, dtype: int64

In [14]:
data.loc['Dallas':'New York', 'two']

Dallas       5
Boston       9
NJ          13
New York    17
Name: two, dtype: int64

In [16]:
data.iloc[1:4, :]

one  two  three  four
Dallas    4    5      6     7
Boston    8    9     10    11
NJ       12   13     14    15

In [17]:
import pandas as pd
df1 = pd.DataFrame({'A': [1, 2, 3], 'B': [4, 5, 6]})
df2 = pd.DataFrame({'A': [7, 8, 9], 'B': [10, 11, 12]})
print(df1)
print(df2)
print("Addition:\n", df1 + df2)
print("\nSubtraction:\n", df1 - df2)
print("\nMultiplication:\n", df1 * df2)
print("\nDivision:\n", df1 / df2)

   A  B
0  1  4
1  2  5
2  3  6
   A   B
0  7  10
1  8  11
2  9  12
Addition:
     A   B
0   8  14
1  10  16
2  12  18

Subtraction:
    A  B
0 -6 -6
1 -6 -6
2 -6 -6

Multiplication:
     A   B
0   7  40
1  16  55
2  27  72

Division:
           A         B
0  0.142857  0.400000
1  0.250000  0.454545
2  0.333333  0.500000


In [18]:
import pandas as pd
df3 = pd.DataFrame({'A': [1,2,3], 'B': [4,5,6]}, index = [0,1,2])
df4 = pd.DataFrame({'A': [7,8,9], 'B': [10,11,12]}, index = [1, 2, 3])
print(df3)
print(df4)
result = df3 + df4
print("Result pf df3 + df4 with alignment: \n", result)

df3 - df4

   A  B
0  1  4
1  2  5
2  3  6
   A   B
1  7  10
2  8  11
3  9  12
Result pf df3 + df4 with alignment: 
       A     B
0   NaN   NaN
1   9.0  15.0
2  11.0  17.0
3   NaN   NaN


A    B
0  NaN  NaN
1 -5.0 -5.0
2 -5.0 -5.0
3  NaN  NaN

In [21]:
import numpy as np
frame = pd.DataFrame(np.random.randn(4, 3), columns=list('bde'),
index=['Utah', 'Ohio', 'Texas', 'Oregon'])
print(frame)
print(np.abs(frame))
f = lambda x: x.max() - x.min()
df_apply = frame.apply(f)
print(df_apply)
df_apply_axis = frame.apply(f, axis='columns') #apply lambda function to columns
print(df_apply_axis)

               b         d         e
Utah   -1.372292  0.745957  0.751667
Ohio    0.572018  0.923324  0.938600
Texas  -0.089345  1.807428  0.301799
Oregon -0.675495 -0.423297  0.826796
               b         d         e
Utah    1.372292  0.745957  0.751667
Ohio    0.572018  0.923324  0.938600
Texas   0.089345  1.807428  0.301799
Oregon  0.675495  0.423297  0.826796
b    1.944310
d    2.230725
e    0.636801
dtype: float64
Utah      2.123959
Ohio      0.366582
Texas     1.896773
Oregon    1.502291
dtype: float64


In [22]:
format = lambda x: '%.2f' % x
df_map = frame['e'].map(format)
print(df_map)

Utah      0.75
Ohio      0.94
Texas     0.30
Oregon    0.83
Name: e, dtype: object


In [23]:
import pandas as pd
import numpy as np
frame = pd.DataFrame({'b': [4, 7, -3, 2], 'a': [0, 1, 0, 1]})
print("I \n",frame)
df_sort_dataframe_by_column = frame.sort_values(by='b')
print("II \n",df_sort_dataframe_by_column)
df_sort_dataframe_by_multiple_columns = frame.sort_values(by=['a', 'b'])
print("III \n",df_sort_dataframe_by_multiple_columns)

I 
    b  a
0  4  0
1  7  1
2 -3  0
3  2  1
II 
    b  a
2 -3  0
3  2  1
0  4  0
1  7  1
III 
    b  a
2 -3  0
0  4  0
3  2  1
1  7  1


In [24]:
obj = pd.Series([7, -5, 7, 3, 2, 0, 4])
df_rank = obj.rank()
print("Rank \n", df_rank)
df_rank_method_first = obj.rank(method='first')
print("rank- Method=first \n", df_rank_method_first)
df_rank_ascending = obj.rank(ascending=False, method='max')
print("rank- Method=max \n", df_rank_ascending)
frame = pd.DataFrame({'b': [4.3, 7, -3, 2], 'a': [0, 1, 0, 1],
'c': [-2, 5, 8, -2.5]})
print("Rank over rows \n", frame)
df_rank_dataframe = frame.rank(axis='columns')
print("Rank over columns \n", df_rank_dataframe)

Rank 
 0    6.5
1    1.0
2    6.5
3    4.0
4    3.0
5    2.0
6    5.0
dtype: float64
rank- Method=first 
 0    6.0
1    1.0
2    7.0
3    4.0
4    3.0
5    2.0
6    5.0
dtype: float64
rank- Method=max 
 0    2.0
1    7.0
2    2.0
3    4.0
4    5.0
5    6.0
6    3.0
dtype: float64
Rank over rows 
      b  a    c
0  4.3  0 -2.0
1  7.0  1  5.0
2 -3.0  0  8.0
3  2.0  1 -2.5
Rank over columns 
      b    a    c
0  3.0  2.0  1.0
1  3.0  1.0  2.0
2  1.0  2.0  3.0
3  3.0  2.0  1.0
